security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Fran\UserBundle\Entity\User: {algorithm: sha512, iterations: 10}

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users_db:
            entity: { class: Fran\UserBundle\Entity\User }
        secured_area:
            id: fran_user_provider
        fos_twitter:
                id: fos_twitter.auth

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern:   /secured/.*
            fos_twitter: true
        public:
            pattern:   /.*
            anonymous: true
            fos_twitter: true
            logout: true
            # oauth:
            #     resource_owners:
            #         # my_github:          "/login/check-github"
            #         # my_google:          "/login/check-google"
            #         # facebook:           "/login/check-facebook"
            #         my_custom:          "/login/check-twitter"
            #     login_path:        /login
            #     failure_path:      /login

            #     oauth_user_provider:
            #         service: fran_user_provider
        # secured_area:
        #     pattern:    ^/secured/
        #     oauth:
        #         oauth_provider:    github
        #         client_id:         %github_client_id%
        #         secret:            %github_client_secret%
        #         scope:             user
        #         check_path:        /secured/login_check
        #         login_path:        /secured/login
        #         failure_path:      /
        #     # form_login:
        #     #     check_path: /secured/login_check
        #     #     login_path: /secured/login
        #     logout:
        #         path:   /secured/logout
        #         target: /
        #     #anonymous: ~
        #     #http_basic:
        #     #    realm: "Secured Demo Area"

        main:
            pattern: ^/
            anonymous: ~
    factories:
        OAuthFactory: "%kernel.root_dir%/../vendor/bundles/HWI/Bundle/OAuthBundle/Resources/config/security_factory.xml"
        FOSTwitterFactory: "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
