security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Fran\UserBundle\Entity\User: {algorithm: sha512, iterations: 10}

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users_db:
            entity: { class: Fran\UserBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/secured/
            provider: users_db
            form_login:
                check_path: /secured/login_check
                login_path: /secured/login
            logout:
                path:   /secured/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        main:
            pattern: ^/
            anonymous: ~
    factories:
        OAuthFactory: "%kernel.root_dir%/../vendor/bundles/Knp/Bundle/OAuthBundle/Resources/config/security_factories.xml"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
