<?php

namespace Fran\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function findWithTaxonomies($id)
	{
		$entity = $this->getEntityManager()
			->createQuery("SELECT p, tax FROM FranPostBundle:Post p JOIN p.taxonomies tax WHERE p.id = :id")
			->setParameter('id', $id)
			->getSingleResult();

        return $entity;
	}
}