<?php

namespace Fran\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyRepository extends EntityRepository
{
}